[workspace]
resolver = "2"
default-members = ["crates/*"]
members = ["crates/*", "contracts/*"]

[workspace.package]
repository = "https://github.com/ahalabs/scaffold-stellar"

[workspace.dependencies]
stellar-scaffold-macro = { path = "crates/stellar-scaffold-macro" }
stellar-registry = { path = "crates/stellar-registry" }

loam-sdk = { version = "0.6.16" }
loam-subcontract-core = { version = "0.7.9" }
stellar-cli = { version = "23.0.0", package = "soroban-cli" }
soroban-rpc = { package = "stellar-rpc-client", version = "23.0.0-rc.5" }
soroban-spec-tools = "23.0.0"

soroban-sdk = "23.0.0-rc.2.1"
stellar-xdr = "23.0.0-rc.2"
stellar-strkey = "0.0.11"

cargo_metadata = "0.18.1"
thiserror = "1.0.38"
sha2 = "0.10.8"

[profile.contracts]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true

[workspace.lints.clippy]
